name: Create Repository
description: Creates and sets up a GitHub repository
branding:
  icon: plus
  color: green
inputs:
  name:
    description: Repository name
    required: true
  owner:
    description: Repository owner
    required: true
    default: ${{ github.repository_owner }}
  description:
    description: Repository description
    required: false
  visibility:
    description: Repository visiblity
    required: false
    default: private
  template:
    description: Template repository (owner/repo)
    required: false
  clone:
    description: Optionally clone the new repository
    required: false
    default: 'false'
  cancel-runs:
    description: Cancel initial workflow runs
    required: true
    default: 'false'
  delete-runs:
    description: Delete initial workflow runs (after cancellation)
    required: true
    default: 'true'
  token:
    description: GitHub personal access token
    required: true
    default: ${{ github.token }}
  
runs:
  using: composite
  steps:

    - name: Create Repository
      id: create-repo
      shell: bash
      env:
        NAME: ${{ inputs.name }}
        OWNER: ${{ inputs.owner }}
        DESCRIPTION: ${{ inputs.description }}
        VISIBILITY: ${{ inputs.visibility }}
        TEMPLATE: ${{ inputs.template }}
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        is_public=$([[ "${VISIBILITY,,}" == "public" ]] && echo true || echo)
        is_private=$([[ "${VISIBILITY,,}" != "public" ]] && echo true || echo)

        gh repo create "$OWNER/$NAME" \
          --description "$DESCRIPTION" \
          ${is_public:+--public} \
          ${is_private:+--private} \
          ${TEMPLATE:+--template "$TEMPLATE"}
          
        if [ -z "$TEMPLATE" ]; then
          exit 0
        fi

        default_branch=$(
          gh api \
            -H "Accept: application/vnd.github.v3+json" \
            "/repos/$TEMPLATE" | \
            jq -r '.default_branch'
        )

        # Wait for initial setup to complete (see https://github.com/cli/cli/issues/5118)
        while ! gh api "/repos/$OWNER/$NAME/branches/$default_branch" &> /dev/null
        do
          sleep 0.5
        done
        sleep 1

    - name: Clone Repository
      shell: bash
      if: inputs.clone == 'true'
      env:
        NAME: ${{ inputs.name }}
        OWNER: ${{ inputs.owner }}
        GITHUB_TOKEN: ${{ inputs.token }}
      run: git clone "https://$GITHUB_TOKEN@github.com/$OWNER/$NAME.git"

    - name: Identify Push Workflows
      id: identify-push-workflows
      shell: bash
      if: inputs.template != '' && inputs.cancel-runs == 'true'
      env:
        OWNER: ${{ inputs.owner }}
        NAME: ${{ inputs.name }}
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        retry() {
          local retries=$1
          shift
          local cmd="$@"
          local i=0
          local exit_code
          local wait
          until eval "$cmd"; do
            exit_code=$?
            i=$(($i + 1))
            if [ $i -lt $retries ]; then
              sleep $i
            else
              return $exit_code
            fi
          done
          return 0
        }

        get_content () {
          local path="$1"
          echo "$(
            gh api \
              -H "Accept: application/vnd.github.v3+json" \
              "/repos/$OWNER/$NAME/contents/$path" |
            jq -r '.content' |
            base64 -d
          )"
        }

        has_push_trigger () { 
          local content=$(retry 5 get_content "'$1'")
          local on=$(echo "$content" | yq '.on')
          local tag="$(echo "$on" | yq 'tag')"
          local has_push_trigger='false'

          case $tag in
            "!!str")
              if [ "$on" = 'push' ]; then
                has_push_trigger='true'
              fi
              ;;

            "!!seq")
              has_push_trigger=$(echo "$on" | yq 'contains(["push"])')
              ;;

            "!!map")
              has_push_trigger=$(echo "$on" | yq 'has("push")')
              ;;
          esac
          
          echo "$has_push_trigger"
        }

        get_workflows() {
          gh api \
            -H "Accept: application/vnd.github+json" \
            "/repos/$OWNER/$NAME/actions/workflows" \
            --jq '.workflows | map({ "id": .id, "path": .path })'
        }

        get_push_workflow_ids() {
          local workflows=$(get_workflows)
          local push_workflow_ids='[]'
          local workflow
          for (( i=0; i<$(echo "$workflows" | jq length); i++ )); do
            workflow=$(echo "$workflows" | jq --argjson i $i '.[$i]')
            if "$(has_push_trigger "$(echo "$workflow" | jq -r '.path')")"; then
              push_workflow_ids=$(echo "$push_workflow_ids" | jq --argjson id "$(echo "$workflow" | jq '.id')" '. += [$id]')
            fi
          done
          echo "$push_workflow_ids" | jq -c
        }

        push_workflow_ids=$(get_push_workflow_ids)
        echo "::set-output name=push-workflow-ids::$push_workflow_ids"

    - name: Cancel Initial Workflow Runs
      shell: bash
      if: inputs.template != '' && inputs.cancel-runs == 'true'
      env:
        NAME: ${{ inputs.name }}
        OWNER: ${{ inputs.owner }}
        TEMPLATE: ${{ inputs.template }}
        DELETE: ${{ inputs.delete-runs }}
        PUSH_WORKFLOW_IDS: ${{ steps.identify-push-workflows.outputs.push-workflow-ids }}
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        retry() {
          local retries=$1
          shift
          local cmd="$@"
          local i=0
          local exit_code
          local wait
          until eval "$cmd"; do
            exit_code=$?
            i=$(($i + 1))
            if [ $i -lt $retries ]; then
              sleep $i
            else
              return $exit_code
            fi
          done
          return 0
        }
        
        list_runs() {
          gh run list \
            --repo "$OWNER/$NAME" \
            --json event,createdAt,databaseId,workflowDatabaseId | \
          jq \
            --argjson push_workflow_ids "$PUSH_WORKFLOW_IDS" \
            '[
              .[] 
              | select( 
                  .event == "push" 
                  and (
                    .workflowDatabaseId as $workflow_id
                    | any($push_workflow_ids; . == $workflow_id)
                  )
                )
            ]'
        }
        
        cancellations_complete() {
          gh run list \
            --repo "$OWNER/$NAME" \
            --json status,databaseId,workflowDatabaseId | \
          jq \
            '
            .[] 
            | all(
                select(
                  .databaseId as $id
                  | any($run_ids; . == $id)
                ); 
                .status == "completed"
              )
            ' \
            --argsjson run_ids "$1"
        }
        
        cancel_run() {
          gh run cancel "$1" --repo "$OWNER/$NAME"
        }
        
        delete_run() {
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github.v3+json" \
            "/repos/$OWNER/$NAME/actions/runs/$1"
        }

        push_workflow_count=$(echo "$PUSH_WORKFLOW_IDS" | jq length)
        timeout=10
        delay=2
        cancelled='[]'
        now=$(date +%s)
        last_cancellation=$now
        while [[ $now < $(($last_cancellation + $timeout)) && $(echo "$cancelled" | jq length) < $push_workflow_count  ]]; do
          runs=$(retry 5 list_runs)
          for (( i=0; i<$(echo "$runs" | jq length); i++ )); do
            run=$(echo "$runs" | jq --argjson i $i '.[$i]')
            run_id=$(echo "$run" | jq -r '.databaseId')
            if [[ ! "$(echo "$cancelled" | jq --argjson id "$run_id" 'any(. == $id)')" ]]; then
              if [[ $now > $(($(date -d "$(echo "$run" | jq -r '.createdAt')" +%s) + $delay)) ]]; then
                retry 5 cancel_run $run_id
                cancelled=$(echo "$cancelled" | jq --argjson id "$run_id" '. += [$id]')
                last_cancellation=$now
              fi
            fi
          done
          sleep 0.5
          now=$(date +%s)
        done
        
        cancelled=$(echo "$cancelled" | jq -c)
        
        # Await run cancellation
        while ! $(retry 5 cancellations_complete "'$cancelled'"); do
          sleep 0.5
        done
        
        # Delete runs
        if $DELETE; then
          for (( i=0; i<$(echo "$cancelled" | jq length); i++ )); do
            run_id=$(echo "$cancelled" | jq --argjson i $i '.[$i]')
            retry 5 delete_run $run_id
          done
        fi
