name: Test
on: [push, pull_request]
concurrency: main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create
        uses: ./
        with:
          name: action-create-repo-test
          owner: nodes-bot
          description: This is a test
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Wait
        run: sleep 3

      - name: Delete Test Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: gh repo delete "nodes-bot/action-create-repo-test" --confirm

      - name: Wait
        run: sleep 3

      - name: Create From Template
        uses: ./
        with:
          name: action-create-repo-test
          owner: nodes-bot
          description: This is a test
          template: actions/javascript-action
          cancel-runs: true
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Wait
        run: sleep 3

      - name: Delete Test Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: gh repo delete "nodes-bot/action-create-repo-test" --confirm

      - name: Wait
        run: sleep 3
      
      - name: Create From Template and Undo Initial Commit
        uses: ./
        with:
          name: action-create-repo-test
          owner: nodes-bot
          description: This is a test
          template: actions/javascript-action
          cancel-runs: true
          undo-initial-commit: true
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Wait
        run: sleep 3

      - name: Delete Test Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: gh repo delete "nodes-bot/action-create-repo-test" --confirm

      - name: Wait
        run: sleep 3

      - name: Create and Clone From Template
        uses: ./
        with:
          name: action-create-repo-test
          owner: nodes-bot
          description: This is a test
          template: actions/javascript-action
          clone: true
          cancel-runs: true
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Wait
        run: sleep 3

      - name: Delete Test Repository
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: gh repo delete "nodes-bot/action-create-repo-test" --confirm
